stages:
  - build
  - test

build site:
  image: node:15
  stage: build
  script:
    - npm i -g npm@7
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

include:
  - template: Code-Quality.gitlab-ci.yml

javascript:
  image: node:15
  stage: test
  script:
    - npm i -g npm@7
    - npm ci
    - npm run test

PHP7.3 + SQLite:
  image: test-nextcloud:latest
  stage: test
  artifacts:
    paths:
      - coverage
  coverage: '/^\s*Lines:\s*(\d+.\d+)\%/'
  script:
    # copy local copy that has been cloned already
    - cp -r . /tmp/inventory
    - mkdir -p /var/www/html ; pushd /var/www/html
    #- wget -q https://download.nextcloud.com/server/releases/nextcloud-16.0.1.zip ; unzip -q nextcloud-16.0.1.zip ; rm nextcloud-16.0.1.zip
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b master nextcloud
    # temporary fix of autoloader.php
    - sed -i $'s|if (substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|if (is_string($root) and substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|g' nextcloud/lib/autoloader.php
    - chown -R www-data:www-data nextcloud && pushd nextcloud/apps && mv /tmp/inventory ./
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "password"
    - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
    # Enable app twice to check occ errors of registered commands
    - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
    # check code with occ
    - sudo -u www-data php /var/www/html/nextcloud/occ app:check-code inventory
    # check PHP code
    - sudo -u www-data make -C /var/www/html/nextcloud/apps/inventory test-php

PHP7.3 + PostgreSQL:
  image: test-nextcloud:latest
  stage: test
  services:
      - postgres:latest
  variables:
      POSTGRES_DB: plop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pgsql-pass"
  script:
    # copy local copy that has been cloned already
    - cp -r . /tmp/inventory
    - mkdir -p /var/www/html ; pushd /var/www/html
    #- wget -q https://download.nextcloud.com/server/releases/nextcloud-16.0.1.zip ; unzip -q nextcloud-16.0.1.zip ; rm nextcloud-16.0.1.zip
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b master nextcloud
    # temporary fix of autoloader.php
    - sed -i $'s|if (substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|if (is_string($root) and substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|g' nextcloud/lib/autoloader.php
    - chown -R www-data:www-data nextcloud && pushd nextcloud/apps && mv /tmp/inventory ./
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:install --database "pgsql" --database-host "postgres:5432" --database-name oc_autotest --database-user postgres --database-pass="pgsql-pass" --admin-user "admin" --admin-pass "password"
    - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
    # Enable app twice to check occ errors of registered commands
    - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
    # check code with occ
    - sudo -u www-data php /var/www/html/nextcloud/occ app:check-code inventory
    # check PHP code
    - sudo -u www-data make -C /var/www/html/nextcloud/apps/inventory test-php

# PHP7.3 + MySQL:
#   image: ubuntu:18.10
#   stage: test
#   before_script:
#     - bash ci/docker_install.sh
#   script:
#     # DB
#     - DEBIAN_FRONTEND=noninteractive apt-get install mariadb-server php7.3-mysql -yqq > /dev/null 2>&1
#     - service mysql start
#     - mysql -u root -e 'create database oc_autotest;'
#     - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
#     - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
#     # copy local copy that has been cloned already
#     - cp -r . /tmp/inventory
#     - mkdir -p /var/www/html ; pushd /var/www/html
#     #- wget -q https://download.nextcloud.com/server/releases/nextcloud-16.0.1.zip ; unzip -q nextcloud-16.0.1.zip ; rm nextcloud-16.0.1.zip
#     - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b master nextcloud
#     # temporary fix of autoloader.php
#     - sed -i $'s|if (substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|if (is_string($root) and substr($fullPath, 0, strlen($root) + 1) === $root . \'/\')|g' nextcloud/lib/autoloader.php
#     - chown -R www-data:www-data nextcloud && pushd nextcloud/apps && mv /tmp/inventory ./
#     - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:install --database "mysql" --database-name oc_autotest --database-user oc_autotest --database-pass="" --admin-user "admin" --admin-pass "password"
#     - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
#     # Enable app twice to check occ errors of registered commands
#     - sudo -u www-data php /var/www/html/nextcloud/occ app:enable inventory
#     - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
#     # check code with occ
#     - sudo -u www-data php /var/www/html/nextcloud/occ app:check-code inventory
#     # check PHP code
#     - sudo -u www-data make -C /var/www/html/nextcloud/apps/inventory test-php
